# Generated by Django 5.1.2 on 2025-09-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcvetok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.TextField(blank=True, null=True, verbose_name='URL-адрес'),
        ),
    ]
