# Generated by Django 5.1.2 on 2025-09-18 09:25

import storages.backends.ftp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcvetok', '0002_attribute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='frameBackground',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(location='ftps://vladanak:vladanak@5.35.90.116:21/'), upload_to='media/frame_backgrounds/', verbose_name='Для фронта бэкграунд'),
        ),
    ]
