# Generated by Django 5.1.2 on 2025-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcvetok', '0003_alter_video_framebackground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_type',
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Аттрибут', 'verbose_name_plural': 'Аттрибуты'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.TextField(default='', verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='display_name',
            field=models.TextField(default='', verbose_name='Отображаемое название'),
        ),
        migrations.DeleteModel(
            name='AttributeType',
        ),
    ]
