# Generated by Django 5.1.2 on 2025-09-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcvetok', '0004_remove_attribute_attribute_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
    ]
