# Generated by Django 5.1.11 on 2025-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcvetok', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='topcvetok_c_parent__e0706b_idx',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='display_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='price_modifier',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
    ]
