# Generated by Django 5.1.11 on 2025-10-02 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcvetok', '0007_remove_category_topcvetok_c_parent__e0706b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='topcvetok.product', verbose_name='Основной товар'),
        ),
    ]
