# Generated by Django 5.1.11 on 2025-10-02 19:54

import django.db.models.deletion
import storages.backends.ftp
import topcvetok.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topcvetok', '0008_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.CharField(default=topcvetok.utils.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена BYN')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена BYN акционная')),
                ('photo', models.ImageField(blank=True, help_text='Фото вариации', null=True, storage=storages.backends.ftp.FTPStorage(location='ftps://vladanak:vladanak@5.35.90.116:21/'), upload_to='media/flowers/', verbose_name='Фото вариации')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='topcvetok.product', verbose_name='Родительский продукт')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Вариации товаров',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topcvetok.productvariant', verbose_name='Вариация'),
        ),
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.CharField(default=topcvetok.utils.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topcvetok.attribute', verbose_name='Значение атрибута')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='topcvetok.productvariant', verbose_name='Вариация')),
            ],
            options={
                'verbose_name': 'Атрибут вариации',
                'verbose_name_plural': 'Атрибуты вариаций',
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_available'], name='topcvetok_p_is_avai_c733da_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='topcvetok_p_price_729a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['created_at'], name='topcvetok_p_created_658940_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantattribute',
            unique_together={('variant', 'attribute')},
        ),
    ]
